server:
  port: 8080
  servlet:
    context-path: /hotelbooking
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
spring:
  datasource:
    url: "jdbc:mysql://localhost:${DBMS_PORT}/${DBMS_NAME}"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  mvc:
    log-resolved-exception: false
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    root: INFO
    org.springframework.security: OFF
    org.springframework.security.access: OFF
    org.springframework.security.authentication: INFO
    org.springframework.security.oauth2: OFF
    org.springframework.web.servlet.DispatcherServlet: OFF
    org.springframework.web.servlet.PageNotFound: OFF
    org.apache.catalina.core.ContainerBase: OFF
    project.hotel_booking_system.config: INFO
    project.hotel_booking_system.exception.GlobalExceptionHandler: OFF
vnpay:
  version: "2.1.0"
  command: "pay"
  locale: "vn"
  currCode: "VND"
  orderType: "billpayment"
  tmnCode: "${TMN_CODE}"
  paymentUrl: "${PAY_URL}"
  hashSecret: "${SECRET_KEY}"
  returnUrl: "${RETURN_URL}"
jwt:
  signer-key: "${SIGNER_KEY}"
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds
