server:
  port: 8080
  servlet:
    context-path: /hotelbooking
spring:
  datasource:
    url: "jdbc:mysql://localhost:${DBMS_PORT}/${DBMS_NAME}"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

